-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 10:49:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carometro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carometro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carometro` DEFAULT CHARACTER SET utf8 ;
USE `carometro` ;

-- -----------------------------------------------------
-- Table `carometro`.`Tipos_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carometro`.`Tipos_Usuarios` (
  `idTipos_Usuarios` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipos_Usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carometro`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carometro`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `Tipos_Usuarios_idTipos_Usuarios` INT NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Tipos_Usuarios1_idx` (`Tipos_Usuarios_idTipos_Usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Tipos_Usuarios1`
    FOREIGN KEY (`Tipos_Usuarios_idTipos_Usuarios`)
    REFERENCES `carometro`.`Tipos_Usuarios` (`idTipos_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carometro`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carometro`.`Turmas` (
  `idTurmas` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NOT NULL,
  `fotos` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTurmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carometro`.`Usuarios_Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carometro`.`Usuarios_Turmas` (
  `Usuarios_idUsuarios` INT NOT NULL,
  `Turmas_idTurmas` INT NOT NULL,
  PRIMARY KEY (`Usuarios_idUsuarios`, `Turmas_idTurmas`),
  INDEX `fk_Usuarios_has_Turmas_Turmas1_idx` (`Turmas_idTurmas` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Turmas_Usuarios_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Turmas_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `carometro`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Turmas_Turmas1`
    FOREIGN KEY (`Turmas_idTurmas`)
    REFERENCES `carometro`.`Turmas` (`idTurmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
